// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKCZuwUvR8lY5vonbTxOwurOihd-RZBt0',
    appId: '1:697389950187:web:fc8c5e3804818acf0a8aae',
    messagingSenderId: '697389950187',
    projectId: 'the-silent-void',
    authDomain: 'the-silent-void.firebaseapp.com',
    storageBucket: 'the-silent-void.appspot.com',
    measurementId: 'G-D7B94NJ552',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXiOghTaO61JvDiyX1dIynRroie1S-qd0',
    appId: '1:697389950187:android:06c7c5f9c23d09590a8aae',
    messagingSenderId: '697389950187',
    projectId: 'the-silent-void',
    storageBucket: 'the-silent-void.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsRrpCm64VTka56L7S8AG7e9Gc4qhpgvY',
    appId: '1:697389950187:ios:5a1d6568b258c5c20a8aae',
    messagingSenderId: '697389950187',
    projectId: 'the-silent-void',
    storageBucket: 'the-silent-void.appspot.com',
    iosBundleId: 'com.example.theSilentVoid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsRrpCm64VTka56L7S8AG7e9Gc4qhpgvY',
    appId: '1:697389950187:ios:82802522025339e50a8aae',
    messagingSenderId: '697389950187',
    projectId: 'the-silent-void',
    storageBucket: 'the-silent-void.appspot.com',
    iosBundleId: 'com.example.theSilentVoid.RunnerTests',
  );
}
